# config/meta.yml

meta_product_name: "We are Unicorn"
meta_title: "We are Unicorn - Manage your charitable investments"
meta_description: "Get to know the real impact of your donation through a streamlined dashboard"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
